services:
  db-expenses:
    container_name: com.henry.expenseTracker.db-expense-tracker
    build:
      dockerfile: ./Dockerfile
      context: ./
    image: h2-alpine
    volumes:
     - ${SRC_DIRECTORY}/db_expenses.sql:/opt/h2-data/db_expenses.sql
    ports:
      - 81:81
      - 1521:1521
    environment:
      H2_OPTIONS: -ifNotExists