spring:
  application:
    name: ExpenseTracker
  datasource:
    driverClassName: org.h2.Driver
    # url: jdbc:h2:mem:~/db_expenses
    url: jdbc:h2:tcp://localhost:1521/db_expenses
    username: sa
    password: test
    platform: h2
  sql:
    init:
      mode: never
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    dialect: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: false # true para que ejecute el data.sql
  data:
    mongodb:
      authentication-database: admin
      host: localhost
      port: 27017
      database: ${MONGO_DB}
      username: ${MONGO_USER}
      password: ${MONGO_PASSWORD}
  output:
    ansi:
      enabled: ALWAYS
logging:
  level:
    root: "warn"
    org.springframework:
      hibernate: 'error'
      web:
        servlet.DispatcherServlet: "debug"
    com.henry.expenseTracker: "info"
  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){magenta} %clr(%-5p) %clr(%c{1}){blue}:%clr(%L){cyan} - %m%n'
server:
  port: 8080
  servlet:
    context-path: / #root route
  error:
    whitelabel:
      enabled: false
    path: /error
