spring:
  application:
    name: ExpenseTracker
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost:1521/db_expenses
    username: sa
    password: test
    #http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8080