spring:
  application:
    name: ExpenseTracker
  output:
    ansi:
      enabled: ALWAYS
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost:1521/db_expenses
    username: sa
    password: test
    #http://localhost:8080/h2-console
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  include-application-name: false
  level:
    root: "warn"
    org.springframework:
      hibernate: 'error'
      web:
        servlet.DispatcherServlet: "debug"
    com.henry.expenseTracker: "info"

  pattern:
    console: '%clr(%d{yyyy-MM-dd HH:mm:ss}){yellow} %clr(%-5p) %clr(%c{1}){blue}:%L - %m%n'
server:
  port: 8080
